Create ethical_statement.md
opendatacam/opendatacam pull request #488
Opened 2021-11-06 17:51 UTC by munsterlander

First draft.  It is a light rip from LPI, although I do feel enough has changed that we are good.  Additionally, as we add and take away, it will move further away from the source document.

2021-11-07 23:45 UTC, munsterlander commented
One thing to note here, I was just browsing and didn't realize that Github has a community section: https://github.com/opendatacam/opendatacam/community where a Code of Conduct based on an open license can be proposed.  Thoughts about just using that?

2021-11-11 14:57 UTC, munsterlander commented
Ok, I put an alternative up.

2021-11-16 20:27 UTC, vsaw requested changes
I stopped reading after [the following line](https://github.com/opendatacam/opendatacam/pull/488/files#diff-246ee8afe584281249b860826a12adc0f237abf2243d3237b28f5983c427fccaR13) as I see this is not what as intended by @tdurand and @b-g

2021-11-16 20:27 UTC, vsaw commented on ethical_statement.md
> +OpenDataCam (ODC) was created as an open-source tool to quantify the world. It is designed to be an accessible, affordable and open-source solution to better understand interactions in urban environm
I think we should put this broader. ODC was also used to count fish (which I personally believe is a perfectly all right use case)

So maybe follow the statement of the website around "quantifying the world"?

2021-11-16 20:27 UTC, vsaw commented on ethical_statement.md
> +This Code of Conduct applies as a condition of use but we expect everyone in our community to follow it.
I'm not a lawyer but this sentence makes it sound like it's part of the End User License Agreement, which as far as I understand is not what has been discussed in https://github.com/opendatacam/opendatacam/issues/390#issuecomment-842417970

> After taking a few days to reflect and spoke with @b-g also, decided to just include in a prominent way something like a "artist statement" on the website / documentation of OpenDataCam for next release... no re licensing, no code of conduct.. keep it very simple as always..

2021-11-19 02:54 UTC, munsterlander reviewed
Works for me.  I was just trying to create a starting point of discussion so 4.0.0 work wouldn't all be left to you guys.

2022-09-20 18:58 UTC, merged